export enum CategoryBook {
    FANTASY = 'FANTASY',
    SCIENCE_FICTION = 'SCIENCE_FICTION',
    MYSTERY = 'MYSTERY',
    ROMANCE = 'ROMANCE',
    HISTORY = 'HISTORY',
    COOKING = 'COOKING',
    ART = 'ART',
}